apiVersion: apps/v1
kind: Deployment
metadata:
  name: whiteboard
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: c001
          image: maulikd2397/whitelabel:latest
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: whiteboard-svc
  labels:
    app: app
spec:
  selector:
    app: app
  type: NodePort
  ports:
    - nodePort: 32767
      port: 80
      targetPort: 8080

